{
 "title": "Snyk Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "query": "query_result(topk(10, sort_desc(sum(snyk_vulnerabilities_total) by (project))))"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Vulnerabilities per Project",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total) by (project)"
    }
   ]
  },
  {
   "title": "$Project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "Project",
   "targets": [
    {}
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Ignored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{ignored=\"true\", project=\"$Project\"})"
    }
   ]
  },
  {
   "title": "Issue Count History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{project=~\"$Project\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Issues by Type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=\"$Project\"}) by (issue_title)"
    }
   ]
  }
 ]
}